version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  install:
     - requirements: Docs/sphinx_doc/requirements.txt

sphinx:
   configuration: Docs/sphinx_doc/conf.py

formats:
  - htmlzip
#  - pdf
#  - epub
