# Dry Cloud Chamber neutral roughness-log heat budget regression.
erf.prob_name = "Cloud Chamber"
erf.init_type = ConstantDensity
erf.anelastic = 1
erf.use_gravity = true
erf.vert_implicit = false
erf.molec_diff_type = ConstantAlpha
erf.dynamic_viscosity = 0.0
erf.alpha_T = 0.001
erf.alpha_C = 0.001
erf.les_type = Smagorinsky
erf.Cs = 0.1
erf.fixed_dt = 0.001
erf.sum_interval = -1
erf.check_int = -1
erf.cloud_chamber_budget_interval = 2
erf.plot_file_1 = plt
erf.plot_int_1 = 2
erf.plot_vars_1 = density theta temp pressure x_velocity y_velocity z_velocity

max_step = 6
geometry.prob_lo = 0.0 0.0 0.0
geometry.prob_hi = 2.0 2.0 1.0
geometry.is_periodic = 0 0 0
amr.n_cell = 16 16 8
amr.max_grid_size = 4
amr.max_level = 0

prob.p_inf = 100000.0
prob.T_0 = 292.0
prob.thermodynamic_initialization = physical_temperature_rh
prob.initial_temperature_bottom = 300.0
prob.initial_temperature_top = 284.0
prob.temperature_perturbation_amplitude = 0.02
prob.perturbation_mode = deterministic_sine

xlo.type = NoSlipWall
xhi.type = NoSlipWall
ylo.type = NoSlipWall
yhi.type = NoSlipWall
zlo.type = NoSlipWall
zhi.type = NoSlipWall

xlo.temperature = 292.0
xlo.moisture = dry
xlo.momentum_transfer_model = resolved_noslip
xlo.heat_transfer_model = neutral_roughness_log
xlo.z0_m = 0.001
xlo.z0_h = 0.0005
xhi.temperature = 292.0
xhi.moisture = dry
xhi.momentum_transfer_model = resolved_noslip
xhi.heat_transfer_model = neutral_roughness_log
xhi.z0_m = 0.001
xhi.z0_h = 0.0005
ylo.temperature = 292.0
ylo.moisture = dry
ylo.momentum_transfer_model = resolved_noslip
ylo.heat_transfer_model = neutral_roughness_log
ylo.z0_m = 0.001
ylo.z0_h = 0.0005
yhi.temperature = 292.0
yhi.moisture = dry
yhi.momentum_transfer_model = resolved_noslip
yhi.heat_transfer_model = neutral_roughness_log
yhi.z0_m = 0.001
yhi.z0_h = 0.0005
zlo.temperature = 300.0
zlo.moisture = dry
zlo.momentum_transfer_model = resolved_noslip
zlo.heat_transfer_model = neutral_roughness_log
zlo.z0_m = 0.001
zlo.z0_h = 0.0005
zhi.temperature = 284.0
zhi.moisture = dry
zhi.momentum_transfer_model = resolved_noslip
zhi.heat_transfer_model = neutral_roughness_log
zhi.z0_m = 0.001
zhi.z0_h = 0.0005
