
// This file is automatically created by parse_erf_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static int state_interp_order;
static int lin_limit_state_interp;
static int do_reflux;
static int do_avg_down;
static amrex::Real CI;
static amrex::Real PrT;
static std::string job_name;

static amrex::Real alpha_T;
static amrex::Real alpha_S;
static amrex::Real dynamicViscosity;
static amrex::Real Cs;
static int         spatial_order;
