import numpy as np
import struct
import os
from pyproj import Proj, Transformer, CRS
from math import *
import subprocess
from pathlib import Path
import math
from mpi4py import MPI
from PIL import Image

def create_gifs_parallel(base_dir, comm):
    rank = comm.Get_rank()
    size = comm.Get_size()

    base_dir = Path(base_dir)
    output_dir = base_dir / "gifs"

    # Only rank 0 needs to make the folder (avoids directory creation race conditions)
    if rank == 0:
        output_dir.mkdir(parents=True, exist_ok=True)

    # Barrier ensures the output directory exists before any rank writes to it
    comm.Barrier()

    # Every rank scans the folder independently — no broadcast needed!
    all_folders = sorted(
        [f for f in base_dir.iterdir() if f.is_dir() and f.name != "gifs"]
    )

    num_folders = len(all_folders)

    # --- Contiguous Block Partitioning ---
    # Calculates start and end indices so early ranks get ceil(N / size) items
    count = math.ceil(num_folders / size)
    start = rank * count
    end = min(start + count, num_folders)

    # Subset of folders assigned to this specific rank
    my_folders = all_folders[start:end]

    # Run loop only on assigned folders
    for folder in my_folders:
        png_paths = sorted(folder.glob("*.png"))

        if not png_paths:
            print(
                f"[Rank {rank}] Skipping '{folder.name}': No PNG files found."
            )
            continue

        gif_filename = output_dir / f"{folder.name}.gif"
        print(
            f"[Rank {rank}] Processing '{folder.name}' ({len(png_paths)} frames)..."
        )

        try:
            # 1. Force convert images to RGB to strip alpha channels
            frames = [Image.open(p).convert("RGB") for p in png_paths]

            # 2. Save GIF without overlay optimization
            frames[0].save(
                gif_filename,
                format="GIF",
                append_images=frames[1:],
                save_all=True,
                duration=200,  # 5 FPS
                loop=0,
                optimize=False,  # <-- SET TO FALSE to prevent frame stacking/ghosting!
                disposal=2,  # <-- DISPOSAL METHOD 2: Clear frame to background before drawing next frame
            )
            print(f"[Rank {rank}]    └─ Created {gif_filename.name}")
        except Exception as e:
            print(
                f"[Rank {rank}]   └─ Error processing '{folder.name}': {e}"
            )

    # Synchronize all ranks before returning to main execution
    comm.Barrier()

def write_binary_vtk_structured_grid(filename,
                                     x_grid,
                                     y_grid,
                                     z_grid,
                                     point_data=None,
                                     velocity=None):
    """
    Writes a binary VTK STRUCTURED_GRID file.

    Grid convention:
        x_grid, y_grid : (ny, nx)
        z_grid         : (ny, nx, nz)

    point_data:
        dictionary of arrays with shape (ny, nx, nz)

    velocity:
        array with shape (ny, nx, nz, 3)
    """

    x_grid = np.asarray(x_grid)
    y_grid = np.asarray(y_grid)
    z_grid = np.asarray(z_grid)

    ny, nx = x_grid.shape
    nz = z_grid.shape[2]

    print("VTK dimensions:", nx, ny, nz)

    with open(filename, 'wb') as f:

        # Header
        f.write(b'# vtk DataFile Version 3.0\n')
        f.write(b'Generated by Python script\n')
        f.write(b'BINARY\n')
        f.write(b'DATASET STRUCTURED_GRID\n')

        f.write(f'DIMENSIONS {nx} {ny} {nz}\n'.encode())

        npoints = nx * ny * nz

        f.write(f'POINTS {npoints} float\n'.encode())

        # ----------------------------
        # Write coordinates
        # ----------------------------
        for k in range(nz):
            for j in range(ny):
                for i in range(nx):

                    x = x_grid[j, i]
                    y = y_grid[j, i]
                    z = z_grid[j, i, k]

                    f.write(struct.pack('>fff',x,y,z))

        # ----------------------------
        # Write point data
        # ----------------------------
        if point_data is not None:

            f.write(f'POINT_DATA {npoints}\n'.encode())

            for name, data in point_data.items():

                if name in ["latitude", "longitude"]:
                    continue

                data = np.asarray(data)

                f.write(f'SCALARS {name} float 1\n'.encode())
                f.write(b'LOOKUP_TABLE default\n')

                for k in range(nz):
                    for j in range(ny):
                        for i in range(nx):

                            value = data[j, i, k]

                            f.write(
                                struct.pack('>f',
                                            float(value))
                            )


        # ----------------------------
        # Velocity vector
        # ----------------------------
        if velocity is not None:

            f.write(
                b'VECTORS velocity float\n'
            )

            velocity = np.asarray(velocity)

            for k in range(nz):
                for j in range(ny):
                    for i in range(nx):

                        vx, vy, vz = velocity[j, i, k]

                        f.write(
                            struct.pack('>fff',
                                        float(vx),
                                        float(vy),
                                        float(vz))
                        )

