import numpy as np
import struct
import os
from pyproj import Proj, Transformer, CRS
from math import *

def write_binary_vtk_structured_grid(filename,
                                     x_grid,
                                     y_grid,
                                     z_grid,
                                     point_data=None,
                                     velocity=None):
    """
    Writes a binary VTK STRUCTURED_GRID file.

    Grid convention:
        x_grid, y_grid : (ny, nx)
        z_grid         : (ny, nx, nz)

    point_data:
        dictionary of arrays with shape (ny, nx, nz)

    velocity:
        array with shape (ny, nx, nz, 3)
    """

    x_grid = np.asarray(x_grid)
    y_grid = np.asarray(y_grid)
    z_grid = np.asarray(z_grid)

    ny, nx = x_grid.shape
    nz = z_grid.shape[2]

    print("VTK dimensions:", nx, ny, nz)

    with open(filename, 'wb') as f:

        # Header
        f.write(b'# vtk DataFile Version 3.0\n')
        f.write(b'Generated by Python script\n')
        f.write(b'BINARY\n')
        f.write(b'DATASET STRUCTURED_GRID\n')

        f.write(f'DIMENSIONS {nx} {ny} {nz}\n'.encode())

        npoints = nx * ny * nz

        f.write(f'POINTS {npoints} float\n'.encode())

        # ----------------------------
        # Write coordinates
        # ----------------------------
        for k in range(nz):
            for j in range(ny):
                for i in range(nx):

                    x = x_grid[j, i]
                    y = y_grid[j, i]
                    z = z_grid[j, i, k]

                    f.write(struct.pack('>fff',x,y,z))

        # ----------------------------
        # Write point data
        # ----------------------------
        if point_data is not None:

            f.write(f'POINT_DATA {npoints}\n'.encode())

            for name, data in point_data.items():

                if name in ["latitude", "longitude"]:
                    continue

                data = np.asarray(data)

                f.write(f'SCALARS {name} float 1\n'.encode())
                f.write(b'LOOKUP_TABLE default\n')

                for k in range(nz):
                    for j in range(ny):
                        for i in range(nx):

                            value = data[j, i, k]

                            f.write(
                                struct.pack('>f',
                                            float(value))
                            )


        # ----------------------------
        # Velocity vector
        # ----------------------------
        if velocity is not None:

            f.write(
                b'VECTORS velocity float\n'
            )

            velocity = np.asarray(velocity)

            for k in range(nz):
                for j in range(ny):
                    for i in range(nx):

                        vx, vy, vz = velocity[j, i, k]

                        f.write(
                            struct.pack('>fff',
                                        float(vx),
                                        float(vy),
                                        float(vz))
                        )

