#!/usr/bin/env python3
"""
Phase 4 Two-Stream Radiation Validation Script
Shortwave Scattering Cloud Test

This script verifies SW flux accuracy for the Meador-Weaver two-stream
diffuse (scattering) flux contribution introduced in Phase 4, combined
with the Phase 3 cloud-layer optical depth enhancement and cloud fraction
blending.

It replicates, level-by-level, the EXACT same algorithm implemented in
compute_sw_layer_two_stream() (ERF_TwoStreamSW.H) and the vertical_two_stream_
sweep() driver (ERF_AdvanceTwoStreamRadiation.cpp), for both the clear-sky
column and the cloudy column, then blends them via cloud_fraction, and
compares against the radiation_sw_scatter_diag.dat output file.

Checks:
1. Surface flux (direct + diffuse, blended) matches the replicated
   analytical calculation (within tolerance)
2. TOA flux matches input solar constant S0 * cos(zenith)
3. All computed fluxes are non-negative
4. Scattering cloud layer produces a nonzero diffuse contribution (sanity
   check that compute_sw_layer_two_stream() is actually being exercised)
"""

import sys
import os
import math

def read_radiation_diag(filename):
    """Read the radiation diagnostic CSV and return a dict of column lists.

    The file is comma separated with a header line
    (step,time,call_site,SW_surface,SW_TOA,SW_up_TOA,LW_net_surface,LW_up_TOA,heating_rate_max,...),
    so columns are looked up by name rather than by position. Non-numeric
    columns (call_site) are kept as strings; numeric columns are floats.
    """
    import csv
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            if reader.fieldnames is None:
                print(f"ERROR: No header found in {filename}")
                return None
            data = {name.strip(): [] for name in reader.fieldnames}
            for row in reader:
                if not any((v or '').strip() for v in row.values()):
                    continue
                for name in reader.fieldnames:
                    key = name.strip()
                    val = (row.get(name) or '').strip()
                    if key == 'call_site':
                        data[key].append(val)
                    elif key == 'step':
                        data[key].append(int(float(val)))
                    else:
                        try:
                            data[key].append(float(val))
                        except ValueError:
                            data[key].append(float('nan'))
    except IOError:
        print(f"ERROR: Could not read {filename}")
        return None

    if not data.get('step'):
        print(f"ERROR: No data found in {filename}")
        return None

    return data

def two_stream_layer(tau, omega, g, mu0):
    """
    Python replica of compute_sw_layer_two_stream() in
    Source/Radiation/ERF_TwoStreamSW.H: reflectance/transmittance of one
    homogeneous layer for diffuse incidence (R_dif, T_dif), the diffuse
    reflectance/transmittance generated by direct incidence (R_dir, T_dir)
    and the direct transmittance T_noscat. Zdunkowski PIFM gamma
    coefficients, Meador-Weaver (1980) layer solution. Must stay in
    numerical sync with the C++ kernel.
    """
    if not (tau > 0.0):
        return 0.0, 1.0, 0.0, 0.0, 1.0

    w0 = min(max(omega, 0.0), 1.0)
    asym = min(max(g, -1.0), 1.0)
    mu0 = min(mu0, 1.0) if mu0 > 0.0 else 1.0

    gamma1 = (8.0 - w0 * (5.0 + 3.0 * asym)) / 4.0
    gamma2 = 3.0 * w0 * (1.0 - asym) / 4.0
    gamma3 = (2.0 - 3.0 * asym * mu0) / 4.0
    gamma4 = 1.0 - gamma3
    alpha1 = gamma1 * gamma4 + gamma2 * gamma3
    alpha2 = gamma1 * gamma3 + gamma2 * gamma4

    k = math.sqrt(max((gamma1 - gamma2) * (gamma1 + gamma2), 1.0e-12))
    E = math.exp(-k * tau)
    E2 = E * E
    D = k * (1.0 + E2) + gamma1 * (1.0 - E2)
    RT = 1.0 / D

    R_dif = max(RT * gamma2 * (1.0 - E2), 0.0)
    T_dif = max(RT * 2.0 * k * E, 0.0)
    if R_dif + T_dif > 1.0:
        sc = 1.0 / (R_dif + T_dif)
        R_dif *= sc
        T_dif *= sc

    k_mu = k * mu0
    if abs(1.0 - k_mu * k_mu) < 1.0e-4:
        k_mu = (1.0 - 1.0e-2) if k_mu < 1.0 else (1.0 + 1.0e-2)
    T_noscat = math.exp(-tau / mu0)
    RT2 = w0 * RT / (1.0 - k_mu * k_mu)
    k_g3 = k * gamma3
    k_g4 = k * gamma4
    R_dir = RT2 * ((1.0 - k_mu) * (alpha2 + k_g3)
                   - (1.0 + k_mu) * (alpha2 - k_g3) * E2
                   - 2.0 * (k_g3 - alpha2 * k_mu) * E * T_noscat)
    T_dir = -RT2 * ((1.0 + k_mu) * (alpha1 + k_g4) * T_noscat
                    - (1.0 - k_mu) * (alpha1 - k_g4) * E2 * T_noscat
                    - 2.0 * (k_g4 + alpha1 * k_mu) * E)
    R_dir = max(R_dir, 0.0)
    T_dir = max(T_dir, 0.0)
    budget = 1.0 - T_noscat
    if R_dir + T_dir > budget:
        sc = budget / (R_dir + T_dir) if (R_dir + T_dir) > 0.0 else 0.0
        R_dir *= sc
        T_dir *= sc
    return R_dif, T_dif, R_dir, T_dir, T_noscat

def compute_column_surface_flux(
        n_layers, dz, tau_base, S0, cos_zenith,
        cloud_base_m, cloud_top_m, cloud_tau_per_layer,
        omega_clear, g_clear, omega_cloud, g_cloud, apply_cloud,
        surface_albedo):
    """
    Python replica of the SW part of vertical_two_stream_sweep()
    (ERF_TwoStreamColumn.H): Beer-Lambert direct beam on the interfaces,
    then the adding method with the surface albedo as the lower boundary
    condition. Interface m = 0 is the surface, m = n_layers the top.
    Returns (F_dir_surface, F_diffuse_down_surface).
    """
    if cos_zenith <= 0.0:
        return 0.0, 0.0

    layers = []
    for m in range(n_layers):
        z = (m + 0.5) * dz
        in_cloud = apply_cloud and (cloud_base_m <= z <= cloud_top_m)
        if in_cloud:
            layers.append((tau_base + cloud_tau_per_layer, omega_cloud, g_cloud))
        else:
            layers.append((tau_base, omega_clear, g_clear))

    # Direct beam on the interfaces, from the top down.
    F_dir = [0.0] * (n_layers + 1)
    F_dir[n_layers] = S0 * cos_zenith
    tau_cum = 0.0
    for m in range(n_layers - 1, -1, -1):
        tau_cum += layers[m][0]
        F_dir[m] = S0 * cos_zenith * math.exp(-tau_cum / cos_zenith)

    props = [two_stream_layer(tau, omega, g, cos_zenith) for (tau, omega, g) in layers]

    # Adding method, upward pass.
    A = [0.0] * (n_layers + 1)
    S = [0.0] * (n_layers + 1)
    A[0] = surface_albedo
    S[0] = surface_albedo * F_dir[0]
    for m in range(n_layers):
        R_dif, T_dif, R_dir, T_dir, _ = props[m]
        denom = max(1.0 - R_dif * A[m], 1.0e-12)
        A[m + 1] = R_dif + T_dif * T_dif * A[m] / denom
        S[m + 1] = R_dir * F_dir[m + 1] + T_dif * (S[m] + A[m] * T_dir * F_dir[m + 1]) / denom

    # Downward pass.
    d_above = 0.0
    d_m = 0.0
    for m in range(n_layers - 1, -1, -1):
        R_dif, T_dif, R_dir, T_dir, _ = props[m]
        denom = max(1.0 - R_dif * A[m], 1.0e-12)
        d_m = (T_dif * d_above + T_dir * F_dir[m + 1] + R_dif * S[m]) / denom
        d_above = d_m

    return F_dir[0], d_m

def read_input_real(inputs_file, key, default):
    """Return the numeric value of `key` from an ERF inputs file, or `default`."""
    try:
        with open(inputs_file, 'r') as f:
            for line in f:
                line = line.split('#', 1)[0].strip()
                if not line or '=' not in line:
                    continue
                k, v = (s.strip() for s in line.split('=', 1))
                if k == key:
                    return float(v.strip('"'))
    except IOError:
        pass
    return default

def check_sw_scattering_cloud_accuracy():
    """Check SW flux accuracy for the Phase 4 scattering + cloud-layer test."""

    diag_file = "radiation_sw_scatter_diag.dat"
    if not os.path.exists(diag_file):
        print(f"ERROR: Diagnostic file {diag_file} not found")
        return False

    data = read_radiation_diag(diag_file)
    if data is None:
        return False

    # Test parameters (must match SW_Scattering_Cloud/inputs)
    S0 = 1361.0
    zenith_deg = 60.0
    cos_zenith = math.cos(math.radians(zenith_deg))
    tau_per_layer = 0.003125
    n_layers = 64
    domain_height_m = 1024.0
    dz = domain_height_m / n_layers

    cloud_base_height_m = 300.0
    cloud_top_height_m = 700.0
    cloud_tau_per_layer = 0.5
    cloud_fraction = 0.5

    # Phase 4 scattering parameters
    omega_clear = 0.0
    g_clear = 0.0
    omega_cloud = 0.9999
    g_cloud = 0.85

    expected_toa_flux = S0 * cos_zenith

    # Surface albedo enters the adding method as the lower boundary condition
    # (erf.radiation.surface_albedo_sw, default 0.3 in RadChoice).
    surface_albedo = read_input_real("inputs", "erf.radiation.surface_albedo_sw", 0.3)

    # Clear-sky column (no cloud enhancement applied at all)
    F_dir_clear, F_diff_clear = compute_column_surface_flux(
        n_layers, dz, tau_per_layer, S0, cos_zenith,
        cloud_base_height_m, cloud_top_height_m, cloud_tau_per_layer,
        omega_clear, g_clear, omega_cloud, g_cloud, False, surface_albedo)
    expected_flux_clear = F_dir_clear + F_diff_clear

    # Cloudy column (cloud-layer optical depth + cloud scattering properties
    # applied within the cloud band)
    F_dir_cloudy, F_diff_cloudy = compute_column_surface_flux(
        n_layers, dz, tau_per_layer, S0, cos_zenith,
        cloud_base_height_m, cloud_top_height_m, cloud_tau_per_layer,
        omega_clear, g_clear, omega_cloud, g_cloud, True, surface_albedo)
    expected_flux_cloudy = F_dir_cloudy + F_diff_cloudy

    # Blended incident surface flux (cloud fraction masking)
    expected_incident_flux = (
        (1.0 - cloud_fraction) * expected_flux_clear
        + cloud_fraction * expected_flux_cloudy
    )

    # The SW_surface diagnostic is the flux absorbed by the surface, i.e. the
    # incident (direct + diffuse) flux times (1 - albedo).
    expected_surface_flux = expected_incident_flux * (1.0 - surface_albedo)

    tolerance = 0.05  # 5%

    print(f"\n{'='*70}")
    print("Phase 4 Two-Stream Radiation: SW Scattering Cloud Test")
    print(f"{'='*70}")
    print(f"\nTest Parameters:")
    print(f"  Solar constant S0 = {S0:.2f} W/m^2")
    print(f"  Solar zenith angle = {zenith_deg:.1f}\u00b0")
    print(f"  cos(zenith) = {cos_zenith:.4f}")
    print(f"  Clear-sky optical depth per layer = {tau_per_layer:.6f}")
    print(f"  Vertical cell spacing dz = {dz:.2f} m")
    print(f"  Cloud layer = [{cloud_base_height_m:.1f}, {cloud_top_height_m:.1f}] m")
    print(f"  Cloud optical depth per layer (added) = {cloud_tau_per_layer:.4f}")
    print(f"  Cloud fraction = {cloud_fraction:.2f}")
    print(f"  Clear-sky (omega, g) = ({omega_clear:.4f}, {g_clear:.4f})")
    print(f"  Cloud (omega, g) = ({omega_cloud:.4f}, {g_cloud:.4f})")
    print(f"\nExpected Fluxes (direct + diffuse):")
    print(f"  Expected TOA flux = {expected_toa_flux:.4f} W/m^2")
    print(f"  Clear-sky column: direct={F_dir_clear:.6e}, diffuse={F_diff_clear:.6e},"
          f" total={expected_flux_clear:.6e} W/m^2")
    print(f"  Cloudy column:    direct={F_dir_cloudy:.6e}, diffuse={F_diff_cloudy:.6e},"
          f" total={expected_flux_cloudy:.6e} W/m^2")
    print(f"  Expected blended incident surface flux = {expected_incident_flux:.6f} W/m^2")
    print(f"  Surface albedo = {surface_albedo:.3f}")
    print(f"  Expected absorbed surface flux = {expected_surface_flux:.6f} W/m^2")

    last_idx = -1
    step = data['step'][last_idx]
    time = data['time'][last_idx]
    SW_surface = data['SW_surface'][last_idx]
    SW_TOA = data['SW_TOA'][last_idx]

    print(f"\nComputed Fluxes (step {step}, time {time:.4f}s):")
    print(f"  Computed TOA flux = {SW_TOA:.4f} W/m^2")
    print(f"  Computed surface flux = {SW_surface:.6f} W/m^2")

    errors = []

    # TOA flux check
    toa_error = abs(SW_TOA - expected_toa_flux) / expected_toa_flux
    print(f"\nAccuracy Checks:")
    print(f"  TOA flux error: {toa_error*100:.2f}%", end="")
    if toa_error > tolerance:
        print(f" [FAIL - exceeds {tolerance*100:.1f}% tolerance]")
        errors.append(f"TOA flux error too large: {toa_error*100:.2f}%")
    else:
        print(" [PASS]")

    # Surface flux check
    if expected_surface_flux > 0:
        surf_error = abs(SW_surface - expected_surface_flux) / expected_surface_flux
        print(f"  Surface flux error: {surf_error*100:.2f}%", end="")
        if surf_error > tolerance:
            print(f" [FAIL - exceeds {tolerance*100:.1f}% tolerance]")
            errors.append(f"Surface flux error too large: {surf_error*100:.2f}%")
        else:
            print(" [PASS]")

    # Non-negativity
    if SW_TOA < 0 or SW_surface < 0:
        errors.append(f"Negative flux detected: TOA={SW_TOA:.4f}, surface={SW_surface:.6f}")
        print(f"  Non-negativity check [FAIL]")
    else:
        print(f"  Non-negativity check [PASS]")

    # Scattering sanity check: the cloudy column's diffuse flux must be
    # strictly positive (confirms compute_sw_layer_two_stream() is actually
    # exercised for the cloud layer), while the clear-sky column's diffuse
    # flux must be exactly zero (confirms omega=0 clear-sky path is
    # unaffected, preserving Phase 1-3/Phase 3 behavior elsewhere).
    print(f"  Clear-sky diffuse flux == 0 (omega_clear=0)?"
          f" diffuse_clear={F_diff_clear:.6e}", end="")
    if F_diff_clear == 0.0:
        print(" [PASS]")
    else:
        print(" [FAIL]")
        errors.append("Clear-sky column diffuse flux is not exactly zero; "
                       "single_scattering_albedo=0 gating is broken")

    print(f"  Cloudy column diffuse flux > 0 (scattering active)?"
          f" diffuse_cloudy={F_diff_cloudy:.6e}", end="")
    if F_diff_cloudy > 0.0:
        print(" [PASS]")
    else:
        print(" [FAIL]")
        errors.append("Cloudy column diffuse flux is not positive; "
                       "compute_sw_layer_two_stream() scattering path not exercised")

    print(f"\n{'='*70}")
    if errors:
        print("TEST FAILED")
        for err in errors:
            print(f"  - {err}")
        return False
    else:
        print("TEST PASSED - SW scattering-cloud fluxes match analytical solution")
        return True

if __name__ == "__main__":
    success = check_sw_scattering_cloud_accuracy()
    sys.exit(0 if success else 1)
