#!/bin/bash
#SBATCH --account=erf
#SBATCH --time=0:15:00
#SBATCH --job-name=DensityCurrent_dz100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --mail-user eliot.quon@nrel.gov
#SBATCH --mail-type BEGIN,END,FAIL

# load environment
. ~/.bash_profile
erf-env

srun -n 32 --cpu_bind=cores ./density_current inputs_wrf_baseline &> log

