add_custom_target(distclean
    # Header
    COMMAND ${CMAKE_COMMAND} -E echo "=========================================="
    COMMAND ${CMAKE_COMMAND} -E echo "Distclean: ${CMAKE_BINARY_DIR}"
    COMMAND ${CMAKE_COMMAND} -E echo "=========================================="
    
    # CMake configuration files (generated by cmake during configuration)
    COMMAND ${CMAKE_COMMAND} -E remove -f 
            CMakeCache.txt          # Main CMake cache
            cmake_install.cmake     # Install script
            Makefile                # Generated Makefile (if using Make generator)
    
    # CTest files (generated by enable_testing() or ctest)
    COMMAND ${CMAKE_COMMAND} -E remove -f
            CTestTestfile.cmake     # CTest configuration
            DartConfiguration.tcl   # CDash/Dart configuration
    
    # Project-specific generated files
    COMMAND ${CMAKE_COMMAND} -E remove -f
            ERFConfig.cmake         # Generated by configure_file() or export()
            compile_commands.json   # Generated by CMAKE_EXPORT_COMPILE_COMMANDS
            git-state.txt           # Custom git state tracking
    
    # CMake-generated directories
    COMMAND ${CMAKE_COMMAND} -E remove_directory 
            CMakeFiles              # CMake build system files
            Testing                 # CTest output
            _deps                   # FetchContent dependencies
    
    # Build output directories (project-specific)
    COMMAND ${CMAKE_COMMAND} -E remove_directory
            Exec                    # Built executables
            Submodules              # Built submodule artifacts
            Tests                   # Built test executables
            bin                     # Binary output directory
            cmake_packages          # CMake package configs
            externals               # External library builds
    
    # pkg-config files (generated by configure_file() for *.pc.in)
    COMMAND ${CMAKE_COMMAND} -E echo "Removing pkg-config files..."
    COMMAND find . -maxdepth 1 -name "*.pc" -type f -delete 2>/dev/null || true
    
    # Built libraries (linker outputs)
    COMMAND ${CMAKE_COMMAND} -E echo "Removing built libraries..."
    COMMAND find . -maxdepth 1 -name "lib*.a" -type f -delete 2>/dev/null || true
    COMMAND find . -maxdepth 1 -name "lib*.so" -type f -delete 2>/dev/null || true
    
    # Build logs (custom logging from build scripts - optional)
    COMMAND ${CMAKE_COMMAND} -E echo "Removing build logs..."
    COMMAND find . -maxdepth 1 -name "build_*.log" -type f -delete 2>/dev/null || true
    
    # Summary
    COMMAND ${CMAKE_COMMAND} -E echo ""
    COMMAND ${CMAKE_COMMAND} -E echo "✓ Distclean complete"
    COMMAND ${CMAKE_COMMAND} -E echo ""
    COMMAND ${CMAKE_COMMAND} -E echo "Note: Install directories preserved"
    
    COMMENT "Removing all CMake configuration and build artifacts"
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)