# Generate one CTest entry per GoogleTest case and MPI rank count.

if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "TEST_EXECUTABLE and OUTPUT_FILE are required")
endif()

foreach(required_var
    MPIEXEC_EXECUTABLE MPIEXEC_NUMPROC_FLAG MPIEXEC_PREFLAGS MPIEXEC_POSTFLAGS
    ERF_MPI_PREFLAGS ERF_MPI_RANKS REPORT_DIRECTORY TEST_TIMEOUT)
  if(NOT DEFINED ${required_var})
    message(FATAL_ERROR "${required_var} is required")
  endif()
endforeach()

foreach(list_var ERF_MPI_PREFLAGS ERF_MPI_RANKS MPIEXEC_PREFLAGS MPIEXEC_POSTFLAGS
                 ERF_CROSSCOMPILING_EMULATOR)
  string(REPLACE "," ";" ${list_var} "${${list_var}}")
endforeach()

if(NOT DEFINED ERF_CROSSCOMPILING_EMULATOR)
  set(ERF_CROSSCOMPILING_EMULATOR)
endif()

separate_arguments(_mpiexec UNIX_COMMAND "${MPIEXEC_EXECUTABLE}")
separate_arguments(_numproc_flag UNIX_COMMAND "${MPIEXEC_NUMPROC_FLAG}")
separate_arguments(_preflags UNIX_COMMAND "${MPIEXEC_PREFLAGS}")
separate_arguments(_postflags UNIX_COMMAND "${MPIEXEC_POSTFLAGS}")

set(_all_preflags ${_preflags} ${ERF_MPI_PREFLAGS})

set(_discovery_command ${ERF_CROSSCOMPILING_EMULATOR} "${TEST_EXECUTABLE}"
  --gtest_list_tests)
execute_process(
  COMMAND ${_discovery_command}
  RESULT_VARIABLE _list_result
  OUTPUT_VARIABLE _list_output
  ERROR_VARIABLE _list_error
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT _list_result EQUAL 0)
  message(FATAL_ERROR
    "GoogleTest discovery failed for ${TEST_EXECUTABLE} (${_list_result}): ${_list_error}")
endif()

file(MAKE_DIRECTORY "${REPORT_DIRECTORY}")
file(WRITE "${OUTPUT_FILE}"
  "# Generated by GenerateERFParallelCTest.cmake; do not edit.\n")

function(_erf_append_arg variable value)
  string(APPEND ${variable} " [==[${value}]==]")
  set(${variable} "${${variable}}" PARENT_SCOPE)
endfunction()

set(_suite "")
set(_case_count 0)
string(REPLACE "\r\n" "\n" _list_output "${_list_output}")
string(REPLACE "\n" ";" _list_lines "${_list_output}")

foreach(_line IN LISTS _list_lines)
  # GoogleTest appends type/value comments to parameterized cases. They are
  # diagnostic only and must not become part of a CTest filter.
  string(REGEX REPLACE "[ \t]*#.*$" "" _line_without_comment "${_line}")
  string(STRIP "${_line_without_comment}" _line_stripped)
  if(_line_stripped STREQUAL "")
    continue()
  endif()

  if(NOT _line MATCHES "^[ \t]")
    if(_line_stripped MATCHES "^(.*)\\.$")
      set(_suite "${CMAKE_MATCH_1}")
    endif()
    continue()
  endif()

  if(_suite STREQUAL "")
    continue()
  endif()

  # Test names emitted by GoogleTest are identifier-like, with optional
  # parameter separators. Keep the parser deliberately narrow so malformed
  # discovery output cannot create arbitrary CMake syntax.
  if(NOT _line_stripped MATCHES "^([A-Za-z0-9_./:-]+)$")
    continue()
  endif()
  set(_test "${CMAKE_MATCH_1}")
  set(_filter "${_suite}.${_test}")

  foreach(_nprocs IN LISTS ERF_MPI_RANKS)
    if(NOT _nprocs MATCHES "^[1-9][0-9]*$")
      message(FATAL_ERROR "Invalid MPI rank count '${_nprocs}'")
    endif()

    set(_name "erf_parallel_tests.${_suite}.${_test}.np${_nprocs}")
    set(_report_identity "${_suite}.${_test}")
    string(MAKE_C_IDENTIFIER "${_report_identity}" _report_stem)
    string(SHA256 _report_hash "${_report_identity}")
    string(SUBSTRING "${_report_hash}" 0 12 _report_hash_short)
    set(_report
        "${REPORT_DIRECTORY}/${_report_stem}-${_report_hash_short}.xml")
    # CTest consumes generated CTestTestfile includes with the legacy
    # add_test(test-name command ...) form. The COMMAND keyword belongs only
    # to CMake's configure-time signature and would become the executable.
    set(_command "add_test(")
    _erf_append_arg(_command "${_name}")
    foreach(_arg IN LISTS _mpiexec _numproc_flag)
      _erf_append_arg(_command "${_arg}")
    endforeach()
    _erf_append_arg(_command "${_nprocs}")
    foreach(_arg IN LISTS _all_preflags)
      _erf_append_arg(_command "${_arg}")
    endforeach()
    foreach(_arg IN LISTS ERF_CROSSCOMPILING_EMULATOR)
      _erf_append_arg(_command "${_arg}")
    endforeach()
    _erf_append_arg(_command "${TEST_EXECUTABLE}")
    _erf_append_arg(_command "--gtest_filter=${_filter}")
    _erf_append_arg(_command "--gtest_output=xml:${_report}")
    foreach(_arg IN LISTS _postflags)
      _erf_append_arg(_command "${_arg}")
    endforeach()
    string(APPEND _command ")\nset_tests_properties(")
    _erf_append_arg(_command "${_name}")
    string(APPEND _command " PROPERTIES LABELS [==[parallel]==]")
    string(APPEND _command " PROCESSORS [==[${_nprocs}]==]")
    string(APPEND _command " TIMEOUT [==[${TEST_TIMEOUT}]==]")
    string(APPEND _command " ENVIRONMENT [==[ERF_PARALLEL_TEST_NPROCS=${_nprocs}]==])\n")
    file(APPEND "${OUTPUT_FILE}" "${_command}")
    math(EXPR _case_count "${_case_count} + 1")
  endforeach()
endforeach()

file(APPEND "${OUTPUT_FILE}"
  "set(ERF_PARALLEL_TEST_DISCOVERED_COUNT ${_case_count})\n")
message(STATUS "Discovered ${_case_count} MPI GoogleTest/rank combinations")
