name: Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  WIN32-MSVC10:
    name: WIN32 MSVC@19.29 - Particles ${{matrix.particles}}
    runs-on: windows-latest
    strategy:
      matrix:
        particles: [OFF, ON]

    steps:

    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Configure Project and Generate Build System
      run: |
        cmake -S . -B build `
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/ERF/install `
          -DCMAKE_BUILD_TYPE:STRING=Debug `
          -DERF_DIM:STRING=3 `
          -DERF_ENABLE_MPI:BOOL=OFF `
          -DERF_ENABLE_PARTICLES:BOOL=${{matrix.particles}} `
          -DERF_ENABLE_TESTS:BOOL=ON `
          -DERF_ENABLE_ALL_WARNINGS:BOOL=OFF `
          -DERF_ENABLE_FCOMPARE:BOOL=ON `
          ${{github.workspace}};

    - name: Compile and Link
      run: |
        cmake --build build --config Debug --parallel 2 --verbose

    - name: Check Unit Test Registration
      shell: pwsh
      run: |
        $out = & "${{runner.workspace}}/ERF/build/Tests/Unit/Debug/erf_unit_tests.exe" --gtest_list_tests
        $out
        $outText = $out -join "`n"
        if ($outText -notmatch '(?m)^[A-Za-z0-9_].*\.$') {
          throw "No unit tests registered"
        }
      working-directory: ${{runner.workspace}}/ERF/build

    - name: CMake Unit Tests
      run: |
        ctest -C Debug -L unit -VV
      working-directory: ${{runner.workspace}}/ERF/build

    - name: CMake Regression Tests # see file ERF/Tests/CTestList.cmake
      run: |
        ctest -C Debug -L regression -VV
      working-directory: ${{runner.workspace}}/ERF/build
