name: Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  WIN32-MSVC10:
    name: WIN32 MSVC@19.29 - MPI ${{ matrix.mpi }} - Particles ${{ matrix.particles }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        particles: [OFF, ON]
        mpi: [ON]        # set to [ON, OFF] if you want both variants

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MS-MPI SDK only
        shell: pwsh
        run: |
          curl -L -o msmpisdk.msi  https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi
          msiexec /i msmpisdk.msi /qn /norestart

          $msmpiInc = 'C:\Program Files (x86)\Microsoft SDKs\MPI\Include'
          $msmpiLib = 'C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64'
          "MSMPI_INC=$msmpiInc" | Out-File -FilePath $env:GITHUB_ENV -Append
          "MSMPI_LIB=$msmpiLib" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Configure (CMake)
        shell: pwsh
        run: |
          cmake -S . -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DERF_ENABLE_MPI=ON `
            -DMPI_CXX_LIB_NAMES=msmpi `
            -DMPI_C_LIB_NAMES=msmpi `
            -DMPI_msmpi_LIBRARY="$env:MSMPI_LIB\msmpi.lib" `
            -DMPI_CXX_INCLUDE_DIR="$env:MSMPI_INC" `
              ${{ github.workspace }}

      - name: Build
        shell: pwsh
        run: cmake --build build --parallel 2 --verbose

      #- name: (Optional) MPI smoke test
      #  if: matrix.mpi == 'ON'
      #  shell: pwsh
      #  run: mpiexec -n 2 cmd /c echo Hello from %COMPUTERNAME%
#

      #- name: CMake Tests
      #  shell: pwsh
      #  working-directory: ${{ runner.workspace }}/ERF/build
      #  run: ctest -L regression -VV